name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - numpy=1.23.3
  - pandas=2.1.3
  - pytest=7.1.2
  - scipy=1.8.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
